### ISSUE TITLE
Unclear points in the spec

### ISSUE THREAD

**Issue by pjt33** [orlp/golf-cpu#1]
1. What does
   
   ```
   # You may assign arbitrary Python expressions to an assembly variable
   # (registers are special objects).
   tmp = a
   ```
   
   mean? We have no context with which to interpret "assembly variable" or "object", and at this point in the spec no idea that `tmp` is not a register but `a` is. And the example is so trivial that it gives no hint as to what the behaviour of e.g. `tmp = a + b * "foo"` would be.
2. How about
   
   ```
       # Arguments may be full Python expressions, as long as they evaluate to
       # a 64-bit integer or a register.
   ```
   
   How does an argument evaluate to a register?
3. In
   
   ```
       in c
       add tmp, c, ord("a") - ord("A") # Equivalent to add a, c, 32.
       out tmp
   ```
   
   what do `in` and `out` do? They're not defined anywhere in the spec.
4. What is the "right thing" in
   
   > A note on the shifts - unlike in C, any value for `b` is allowed and does the right thing on the GOLF.
   
   ? Does it shift by `b & 63`, as Java?
5. What are the Boolean values generated by the various comparisons?
6. Do the partial width stores leave the other bytes of the target register intact?

**Comment by orlp** [comment]
Thanks for your feedback.
1. All assignments and expressions are evaluated in [a custom Python environment](https://github.com/orlp/golf-cpu/blob/master/as.py#L222). In this environment there are 27 pre-initialized variables: `a`-`z` and `data`. If you were to run `print(a)` you'd get back `Reg('a')`. This is a register object. It is a placeholder for a register, and will be replaced by a register in the final binary.
   
   When you write an assignment in _GOLF_ assembly it adds a new name as a synonym to the environment. Similarly a label adds a new name to the environment to a label object that will be replaced by an offset to the following instruction in the final binary.
2. An argument evaluates to a register if the expression for that argument evaluates to a register object. So for example `[a, b][1]` evaluates to register b.
3. `in` and `out` were part of an early draft, but apparently I forgot to edit them out. I'll fix that.
4. In C a shift has undefined behavior if the shift width is too big (think `1 << 1000`) or if it's negative (`2 << -1`). In _GOLF_ a shift can have any width (shifts bigger than 64 always result in `0`), and a negative shift flips the shift direction (`2 << -1 == 2 >> 1`).
5. `0` for false, `1` for true.
6. You can't store into a register, only into memory. Neighboring memory bytes are left untouched.
