### ISSUE TITLE
Can't use register e due to collision with math library

### ISSUE THREAD

**Issue by robertcampion** [orlp/golf-cpu#11]
MWE:

```
mov e, 0
halt 0
```

Assembler output:

```
robert@unity:~/golf$ ./assemble.py mwe.golf
Traceback (most recent call last):
  File "./assemble.py", line 370, in <module>
    binary, debug = assemble(lines)
  File "./assemble.py", line 304, in assemble
    instructions = preprocess(lines)
  File "./assemble.py", line 297, in preprocess
    check_instr_arguments(ident, args, lnr, lines)
  File "./assemble.py", line 157, in check_instr_arguments
    .format(instr, sig[0], lnr + 1, lines[lnr]))
SyntaxError: 'mov' requires 1 output register(s) on line 1:
mov e, 1
```

---

The problem originates in lines 240 and 241:

```
variables = {c: Reg(c) for c in string.ascii_lowercase}
variables.update(dict([mem for mem in inspect.getmembers(math) if not mem[0].startswith("_")]))
```

We add the register `e`, but then it gets overwritten by `math`'s `e`.  I think the solution is to, instead of adding all of `math`'s members, just add `math` itself.  We can then use `math.e` to get Euler's constant, and `e` to get register `e`.  We'll have to append `math.` to all the math functions, but I don't see any other way to avoid collision.

**Comment by orlp** [comment]
Registers now overwrite math functions, and `math` is now also exported. E.g.:

```
mov e, int(math.e)
halt e
```

Exits with 2.
