### ISSUE TITLE
Incorrect error message when writing/reading I/O using wrong data size

### ISSUE THREAD

**Issue by edc65** [orlp/golf-cpu#2]
This message : "May only use lw/sw for stdin/stdout." should use "lb/sb"

**Comment by orlp** [comment]
@edc65 No, `lw`/`sw` are intentional.

You need to be able to get `-1` for EOF. This is also the reason why `getc()` in C returns an int.

**Comment by edc65** [comment]
So the message is ok, but the code is wrong? 
if width != 8: raise RuntimeError("May only use lw/sw for stdin/stdout.")
Should be width != 16
