### ISSUE TITLE
sal can't be a pseudoinstruction

### ISSUE THREAD

**Issue by randall77** [orlp/golf-cpu#3]
```
sal a, a, -2
```

is that equivalent to
    shr a, a, 2
or
    sar a, a, 2
?

The pseudoinstruction sal is replaced with shl.  So currently the system will always pick option #1.  You probably want to get option #2 .

**Comment by orlp** [comment]
Good point, usually `sal` is a pseudoinstruction because CPUs don't implement negative shifts - the GOLF however does. So I'll change it to a real instruction.

**Comment by orlp** [comment]
Fixed in https://github.com/orlp/golf-cpu/commit/7427ea7047639b922a0ae3c6f5951df9e825dc30.
