### ISSUE TITLE
Missing cycle costs

### ISSUE THREAD

**Issue by randall77** [orlp/golf-cpu#4]
Currently golf.py assigns cost 0 to ret and halt.  The spec says 1 and 9, respectively.

**Comment by orlp** [comment]
`halt` should be 0 - I must've accidently hit 9 when writing the docs. I'll change that in the docs.

`ret` is incorrectly implemented as zero cost - I'll fix that.

**Comment by orlp** [comment]
Fixed with https://github.com/orlp/golf-cpu/commit/c5ff56453d4796e28c8eb3b2907ba23d91284afb.
