### ISSUE TITLE
Pop/push not working across function calls?

### ISSUE THREAD

**Issue by csaftoiu** [orlp/golf-cpu#6]
I tried the following:

```
call main
pop a, z
halt 0

main:
    mov c, 10
    mov b, 20
    add a, c, b
    push z, a
    ret
```

And I get the following error:

```
$ python3 golf-cpu/assemble.py -r bad.s
Traceback (most recent call last):
  File "golf-cpu/assemble.py", line 345, in <module>
    sys.exit(golf.GolfCPU(binary).run())
  File "/Users/csaftoiu/PycharmProjects/codegolf/GOLFC/golf-cpu/golf.py", line 196, in run
    self.execute_instr(instr_name, instr_args)
  File "/Users/csaftoiu/PycharmProjects/codegolf/GOLFC/golf-cpu/golf.py", line 154, in execute_instr
    elif instr == "lw":   self.regs[args[0]] = self.load(args[1], 8)
  File "/Users/csaftoiu/PycharmProjects/codegolf/GOLFC/golf-cpu/golf.py", line 88, in load
    return struct.unpack("<" + fmts[width], bytes(r))[0]
struct.error: unpack requires a bytes object of length 8
```

Am I doing something wrong or is this a bug? The following works fine:

```
    mov c, 10
    mov b, 20
    add a, c, b
    push z, a
    pop a, z
    halt 0
```

Also should it be `ret z` or would `ret` itself imply the `z`?

**Comment by orlp** [comment]
`z` is always implied in `call`/`ret` - it is **never** restored - AKA always returned.

However I should give a better error message for this, right now it generates buggy code if you put it in the argument list.

**Comment by csaftoiu** [comment]
Ah okay. The same bug persists even if I do a blank `ret` or a `ret e`, for example. It doesn't appear to be caused specifically by me having done `ret z`. I updated the example in the first message.

**Comment by orlp** [comment]
Fixed in https://github.com/orlp/golf-cpu/commit/4c200bfe59d8053eac4a600d63b5c3cb28949db0.

Thanks for your feedback.

**Comment by csaftoiu** [comment]
Awesome! Thanks for the quick turn-around. I started playing around with a C->GOLF compiler [here](https://github.com/csaftoiu/GOLF-C) if you're interested. Now it successfully compiles `int main() { return 10 + 20; }` into essentially the example above.
