### ISSUE TITLE
Halt does not work with a register argument

### ISSUE THREAD

**Issue by csaftoiu** [orlp/golf-cpu#7]
With the following code:

```
mov a, 30
halt a
```

I would expect the program to exit with exit code 30. However, it instead prints "a" and exits with error code 1.

**Comment by orlp** [comment]
This is a bug, I'll look into it soon.

**Comment by orlp** [comment]
Fixed with https://github.com/orlp/golf-cpu/commit/45d1c29f6b5e6373177c336663171d79874d833e .
