### ISSUE TITLE
Add pseudo-instructions in and out

### ISSUE THREAD

**Issue by tyilo** [orlp/golf-cpu#9]
It would be nice to have the pseudo-instructions `in` and `out`, which would both take a single register as argument and just use `lw`/`sw` on the address `-1`.

```
in r -> lw r, -1
out r -> sw -1, r
```

**Comment by orlp** [comment]
I'm a bit conflicted on this. On one hand this is just nice to have.

On the other hand I'd like to keep the _GOLF_ assembler language pure, and think of the idea that the memory address `0xffffffffffffffff` is special is just a detail of how I/O is done on the _GOLF_ machine.

**Comment by orlp** [comment]
I'm not implementing this, it's not the assembler's job to keep track of how I/O is done at a particular chip.
